title: Portfolio de Yanis
email: yanis.rouag@epitech.eu
description: Portfolio Ã©tudiant Epitech.
url: "https://autaweb.github.io"


baseurl: "/PORTFOLIO"

collections:
  projects:
    output: true
    permalink: /projects/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap